### ISSUE TITLE
Labels not correctly positioned in BernsteinPolynomials applet

### ISSUE THREAD

**Issue by tarekt** [happah-graphics/happah-applets#28]
The labels are all on a horizontal line and jump to their actual position as soon as an update was triggered.
-> Move some code from update into the constructor to get correct positions on startup.

**Comment by tarekt** [comment]
This is a general problem on every applet with labels.
Somehow the labels will not update positions on update, however
when an update event is triggered, the labels move to the correct position.

**Comment by secuvim** [comment]
We should look into the underlying problem, why shooting an event at the end of the applet creation isn't processed. Does it happen before the applet is fully initialized?

**Comment by tarekt** [comment]
Found the problem:
the projection matrix of the camera was not up to date, so the parent object's position was not projected onto the screen plane. Fixed by calling an update in the applet's main.js.
